/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const icons: typeof import('@/data/images').icons
  const images: typeof import('@/data/images').images
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly icons: UnwrapRef<typeof import('@/data/images')['icons']>
    readonly images: UnwrapRef<typeof import('@/data/images')['images']>
  }
}